### ISSUE TITLE
Moksha Background --> Jumping when open Chromium

### ISSUE THREAD

**Issue by andybehre** [JeffHoogland/moksha#30] opened 2015-12-31 11:01 UTC
Hello Jeff,

I use Bodhi Linux with actual Moksha desktop (0.1.0.).
When I start Chromium browser (which is maximized) the background image is jumping on the right screen side for about 20px (seems exactli the same witdh as the scrollbars from chromium)...
Maybe you find solution...

Regards

Andreas

**Comment by JeffHoogland** [comment] 2015-12-31 16:22
Your moksha background is "jumping"? Does that mean it is moving itself or?... Can you post a screenshot of what you are seeing?

**Comment by andybehre** [comment] 2015-12-31 16:48
Hello Jeff,

yes, the background image is moving (jumping) to the left for about 20px 
I think.
It happens, when I open Chromium, right before the chromium window is 
opening the background image is jumping to the left.
It's so short, that I couldn't take a proper screenshot...
Hope my explanation is better to understand, what's happening...

Regards

Andreas

Am 31.12.2015 um 17:22 schrieb Jeff Hoogland:

**Comment by JeffHoogland** [comment] 2015-12-31 16:52
If it happens for just a split second and then corrects itself is it really an issue?

**Comment by andybehre** [comment] 2015-12-31 17:57
It's not an system relevant issue, it's "only" an cosmetic issue.
I reported it here for you to improve moksha ;-)

Regards

Andreas


Am 31.12.2015 um 17:52 schrieb Jeff Hoogland:

**Comment by JeffHoogland** [comment] 2015-12-31 17:57
Can't reproduce anything similar here and I use Chrome constantly.

**Closed by JeffHoogland** 2015-12-31 17:57 UTC

**Comment by andybehre** [comment] 2015-12-31 18:09
I use chromium, maybe only here not on chrome?


Am 31.12.2015 um 18:57 schrieb Jeff Hoogland:
