### ISSUE TITLE
Starter Icons on Desktop

### ISSUE THREAD

**Issue by andybehre** [JeffHoogland/moksha#31] opened 2015-12-31 11:09 UTC
Hello Jeff,

your I like Bodhi with Moksha very much, the only Thing I'm missing seriously is the possibility to place Starter Icons for Applications directly on desktop an arrange / group it to my needs.
For now I work around with an IBar, placed on Desktop, but this solution is difficult do get it done and you can't place the icons depending to your personal needs on desktop, only vertical or horizontal.

Maybe you can add the functionality under "add to favourites":
right-click on application bar --> application name --> "add to desktop"

This functionality whould be a great pleasure for all the windows to linux switcher...

Regards

Andreas

**Comment by JeffHoogland** [comment] 2015-12-31 16:24
You can add any number of ibars to your desktop. Simply create a new ibar for each launcher you want and move them around however you want. I agree that a cleaner / less steps method of doing this would be ideal though. 

For now I am marking this as closed because it is already possible, but it is still an improvement we can make at some point (not a bug). The current gadget placing dialog is confusing at clunky at best.

**Closed** 2015-12-31 16:25 UTC

**Comment by kaihu** [comment] 2016-01-03 08:17
You can create symbolic links for `.desktop` files from `~/.local/share/applications` and `/usr/share/applications` to `~/Desktop` (this path may be localized on your system) and you will have application launchers on your desktop which you can organize as you wish.

This feature could be a reasonable addition to context menus for ibar icons. Another place to add this in would be the personal launcher dialog.
